## Imports

In [1]:
import pandas as pd
import numpy as np
from scipy import sparse
from scipy.sparse import csr_matrix, lil_matrix
import pickle
import math

## Creating global containers for holding stats

In [5]:
n = 61188
weights = np.random.rand(20, n)
print(weights)
sparse_training_data = sparse.load_npz('sparse_training.data.npz')
print(sparse_training_data[1,11])


[[0.09205118 0.3246045  0.58871842 ... 0.9031311  0.36886161 0.80232555]
 [0.46682913 0.34883097 0.5903606  ... 0.77611167 0.53929132 0.87098131]
 [0.88643658 0.30520703 0.68186699 ... 0.43281215 0.29342336 0.09643033]
 ...
 [0.29728378 0.55925738 0.72654318 ... 0.34723186 0.88084276 0.03567184]
 [0.30573294 0.40492784 0.90927709 ... 0.29228023 0.3350636  0.03065301]
 [0.03564761 0.44471199 0.732939   ... 0.0719653  0.30122581 0.0956072 ]]
4336
